
-- +goose Up
CREATE TABLE t_follow (
id		SERIAL PRIMARY KEY,
follower_id	INTEGER REFERENCES t_user(id) ON DELETE CASCADE,
followed_id	INTEGER REFERENCES t_user(id) ON DELETE CASCADE,
ctime		TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
mtime		TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);


-- +goose Down
DROP TABLE t_follow;
