// Code generated by protoc-gen-go.
// source: tweetlite.proto
// DO NOT EDIT!

/*
Package twit is a generated protocol buffer package.

It is generated from these files:
	tweetlite.proto

It has these top-level messages:
	TweetLite
*/
package twit

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type TweetLite struct {
	Id               *int32 `protobuf:"varint,1,req,name=Id" json:"Id,omitempty"`
	UserId           *int32 `protobuf:"varint,2,req,name=UserId" json:"UserId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TweetLite) Reset()                    { *m = TweetLite{} }
func (m *TweetLite) String() string            { return proto.CompactTextString(m) }
func (*TweetLite) ProtoMessage()               {}
func (*TweetLite) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TweetLite) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TweetLite) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*TweetLite)(nil), "twit.TweetLite")
}

var fileDescriptor0 = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x29, 0x4f, 0x4d,
	0x2d, 0xc9, 0xc9, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x29, 0xcf,
	0x2c, 0x51, 0x52, 0xe7, 0xe2, 0x0c, 0x01, 0x49, 0xf8, 0x00, 0x25, 0x84, 0xb8, 0xb8, 0x98, 0x3c,
	0x53, 0x24, 0x18, 0x15, 0x98, 0x34, 0x58, 0x85, 0xf8, 0xb8, 0xd8, 0x42, 0x8b, 0x53, 0x8b, 0x80,
	0x7c, 0x26, 0x10, 0x1f, 0x10, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xa0, 0xea, 0x7b, 0x40, 0x00, 0x00,
	0x00,
}
