// Code generated by protoc-gen-go.
// source: protobuf/test.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	protobuf/test.proto

It has these top-level messages:
	Timeline
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type FOO int32

const (
	FOO_X FOO = 17
)

var FOO_name = map[int32]string{
	17: "X",
}
var FOO_value = map[string]int32{
	"X": 17,
}

func (x FOO) Enum() *FOO {
	p := new(FOO)
	*p = x
	return p
}
func (x FOO) String() string {
	return proto.EnumName(FOO_name, int32(x))
}
func (x *FOO) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FOO_value, data, "FOO")
	if err != nil {
		return err
	}
	*x = FOO(value)
	return nil
}
func (FOO) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Timeline struct {
	Tweets           []*Timeline_Tweet `protobuf:"bytes,1,rep,name=Tweets" json:"Tweets,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Timeline) Reset()                    { *m = Timeline{} }
func (m *Timeline) String() string            { return proto.CompactTextString(m) }
func (*Timeline) ProtoMessage()               {}
func (*Timeline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Timeline) GetTweets() []*Timeline_Tweet {
	if m != nil {
		return m.Tweets
	}
	return nil
}

type Timeline_Tweet struct {
	Id               *string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	UserId           *string `protobuf:"bytes,2,opt,name=UserId" json:"UserId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Timeline_Tweet) Reset()                    { *m = Timeline_Tweet{} }
func (m *Timeline_Tweet) String() string            { return proto.CompactTextString(m) }
func (*Timeline_Tweet) ProtoMessage()               {}
func (*Timeline_Tweet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Timeline_Tweet) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Timeline_Tweet) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*Timeline)(nil), "protobuf.Timeline")
	proto.RegisterType((*Timeline_Tweet)(nil), "protobuf.Timeline.Tweet")
	proto.RegisterEnum("protobuf.FOO", FOO_name, FOO_value)
}

var fileDescriptor0 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0xf3, 0x84, 0x38, 0x60, 0x82,
	0x4a, 0x91, 0x5c, 0x1c, 0x21, 0x99, 0xb9, 0xa9, 0x39, 0x99, 0x79, 0xa9, 0x42, 0x1a, 0x5c, 0x6c,
	0x21, 0xe5, 0xa9, 0xa9, 0x25, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x12, 0x7a, 0x30,
	0x65, 0x7a, 0x30, 0x35, 0x7a, 0x60, 0x05, 0x52, 0xca, 0x5c, 0xac, 0x60, 0x86, 0x10, 0x17, 0x17,
	0x93, 0x67, 0x0a, 0x50, 0x39, 0xa3, 0x06, 0xa7, 0x10, 0x1f, 0x17, 0x5b, 0x68, 0x71, 0x6a, 0x11,
	0x90, 0xcf, 0x04, 0xe2, 0x6b, 0xf1, 0x70, 0x31, 0xbb, 0xf9, 0xfb, 0x0b, 0xb1, 0x72, 0x31, 0x46,
	0x08, 0x08, 0x02, 0x02, 0x00, 0x00, 0xff, 0xff, 0x78, 0x42, 0x4f, 0x64, 0x88, 0x00, 0x00, 0x00,
}
